openapi: 3.0.0
info:
  title: Proyek
  version: 1.0.0
servers:
  - url: https://130.162.195.228
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Pasien
  - name: Auth
  - name: Dokter
paths:
  /mhs714220011/pasien:
    get:
      tags:
        - Pasien
      summary: Read
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Pasien
      summary: Post
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nama_lengkap: Nuril
                nik: '3019735829777'
                jenis_kelamin: Pria
                tempat_lahir: Bandung
                tanggal_lahir: '2023-11-28'
                alamat: Jl. Batununggal
                no_hp: '081802867302'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220011/pasien/{id}:
    delete:
      tags:
        - Pasien
      summary: Delete
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 251
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220011/login:
    post:
      tags:
        - Auth
      summary: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: nunu
                password: '123'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220011/regis:
    post:
      tags:
        - Auth
      summary: register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: nunu
                password: '123'
                email: 123@gmail.com
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220011/dokter:
    get:
      tags:
        - Dokter
      summary: Read
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Dokter
      summary: Post
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nid: 1142200020
                nama: Ukasyah
                keahlian: Gigi
                no_hp: '0895379114998'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220011/dokter/{id}:
    put:
      tags:
        - Dokter
      summary: Put
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nid: 1142200020
                nama: Ukasyah
                keahlian: Jantung
                no_hp: '0895379114998'
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 13
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Dokter
      summary: Delete
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 13
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
